### ISSUE TITLE
Release `reliable_udp_comms` package?

### ISSUE THREAD

**Issue by RonghaiHe** [MIT-SPARK/Kimera-Distributed#3]
I got to know that the remote topic manager module is implemented by ENet, which is further developed as a package: `reliable_udp_comms`. How about releasing that package?

**Comment by yunzc** [comment]
Hi @RonghaiHe unfortunately `reliable_udp_comms` is a package from a collaborator and we have not been able to open source it. 
In this issue there is a suggested alternative: https://github.com/MIT-SPARK/Kimera-Multi/issues/25, but I have not tried it out myself.

**Comment by RonghaiHe** [comment]
Got it. Thanks.
